"""Generate shep's mark from the typeface it actually ships.

Candidate B: the board's copper selection marker `▌` beside a large `s`.
The `s` is JetBrains Mono Bold's own glyph rather than a redrawing of it, so
the icon and the app are literally the same letterform. The marker is drawn
as a rectangle because that is exactly what `▌` is — a half-filled cell —
and its width is taken from the glyph's real proportion (300/600 of a cell).

Two sizes come out of here, because they solve different problems:

  launcher (viewport 108) — Android's safe zone is the inner 72dp, but a
  *circular* mask inscribes a 72dp circle in it, so what has to fit is a
  radius of 36 from centre, not a 72dp square. The mark's farthest corner
  sits at r≈34.

  notification (viewport 60) — drawn at 24dp and tinted white in a status
  bar, so it has to nearly fill its box. The launcher's 48% fill would be a
  speck.
"""
import math, pathlib, sys
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Transform

FONT = '/Users/alex/vault/dev/shep-android/app/src/main/res/font/jetbrains_mono_bold.ttf'
f = TTFont(FONT); gs = f.getGlyphSet(); cmap = f.getBestCmap()

PANEL, COPPER, TEXT = "#1D1813", "#E09A55", "#ECE6DF"
S_LSB_U, S_W_U, S_XH_U = 67, 538 - 67, 559     # the `s` glyph in font units
BLOCK_W_U, GAP_U = 300, 82                     # half a cell, and the gap after it


def mark(viewport: float, fill: float):
    """Return (block_path, s_path, radius) for a mark filling `fill` of `viewport`."""
    centre = viewport / 2
    width_u = BLOCK_W_U + GAP_U + S_W_U
    scale = viewport * fill / width_u
    block_w = BLOCK_W_U * scale
    block_h = viewport * fill * 0.848          # the marker is taller than the x-height
    s_w = S_W_U * scale
    x_height = S_XH_U * scale
    left = centre - (viewport * fill) / 2
    s_left = left + block_w + GAP_U * scale
    baseline = centre + x_height / 2

    r = lambda v: f"{v:.2f}".rstrip('0').rstrip('.')
    x0, y0 = left, centre - block_h / 2
    x1, y1 = x0 + block_w, y0 + block_h
    block = f"M{r(x0)},{r(y0)} L{r(x1)},{r(y0)} L{r(x1)},{r(y1)} L{r(x0)},{r(y1)} Z"

    pen = SVGPathPen(gs, ntos=lambda v: f"{v:.2f}".rstrip('0').rstrip('.'))
    gs[cmap[ord('s')]].draw(
        TransformPen(pen, Transform(scale, 0, 0, -scale, s_left - S_LSB_U * scale, baseline))
    )
    return block, pen.getCommands(), math.hypot(centre - left, block_h / 2), s_w


LAUNCHER = mark(108, 0.48)
NOTIF = mark(60, 0.86)

HEAD = '''<?xml version="1.0" encoding="utf-8"?>
<!--
  {title}

  shep's mark: the board's `▌` selection marker beside JetBrains Mono Bold's
  own `s`, extracted from the bundled font rather than redrawn — so the icon
  and the app share a letterform. Generated by scratchpad/icon/gen.py; edit
  that, not this.
-->
'''


def vector(title, block_fill, s_fill, geom, viewport, size, tint=""):
    block, sglyph, _, _ = geom
    return HEAD.format(title=title) + f'''<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size}dp"
    android:height="{size}dp"
    android:viewportWidth="{viewport}"
    android:viewportHeight="{viewport}"{tint}>
    <path
        android:fillColor="{block_fill}"
        android:pathData="{block}" />
    <path
        android:fillColor="{s_fill}"
        android:pathData="{sglyph}" />
</vector>
'''


def svg(geom, viewport, mono=False):
    block, sglyph, _, _ = geom
    bg = "none" if mono else PANEL
    b = "#DDD9D2" if mono else COPPER
    t = "#DDD9D2" if mono else TEXT
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {viewport} {viewport}" '
            f'width="{viewport}" height="{viewport}" role="img" aria-label="shep">\n'
            f'  <title>shep</title>\n'
            + (f'  <rect width="{viewport}" height="{viewport}" rx="24" fill="{bg}"/>\n' if not mono else '')
            + f'  <path fill="{b}" d="{block}"/>\n  <path fill="{t}" d="{sglyph}"/>\n</svg>\n')


def shortcut():
    """The `+ new` launcher shortcut, in the same typeface as the words.

    `@android:drawable/ic_input_add` was a stock system glyph, which on a
    home screen sits directly under the app's own mark — two different
    drawing hands, one centimetre apart.
    """
    vp, fill = 108.0, 0.42
    centre = vp / 2
    n = cmap[ord('+')]
    bp_scale = vp * fill / 500          # the `+` is roughly 500 units across
    pen = SVGPathPen(gs, ntos=lambda v: f"{v:.2f}".rstrip('0').rstrip('.'))
    from fontTools.pens.boundsPen import BoundsPen
    bp = BoundsPen(gs); gs[n].draw(bp)
    x0, y0, x1, y1 = bp.bounds
    sc = vp * fill / (x1 - x0)
    gs[n].draw(TransformPen(pen, Transform(
        sc, 0, 0, -sc,
        centre - (x0 + x1) / 2 * sc,
        centre + (y0 + y1) / 2 * sc,
    )))
    return HEAD.format(title="Launcher shortcut: new task") + f'''<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="{PANEL}"
        android:pathData="M0,0 L108,0 L108,108 L0,108 Z" />
    <path
        android:fillColor="{COPPER}"
        android:pathData="{pen.getCommands()}" />
</vector>
'''


out = pathlib.Path(sys.argv[1]); out.mkdir(parents=True, exist_ok=True)
(out / "ic_shortcut_new_task.xml").write_text(shortcut())
(out / "ic_launcher_foreground.xml").write_text(
    vector("Launcher icon, foreground layer", COPPER, TEXT, LAUNCHER, 108, 108))
(out / "ic_launcher_monochrome.xml").write_text(
    vector("Launcher icon, monochrome layer (Android 13 themed icons)",
           "#FFFFFF", "#FFFFFF", LAUNCHER, 108, 108))
(out / "ic_notification.xml").write_text(
    vector("Notification small icon — replaces stat_sys_warning, which told "
           "every notification shep sent that something was wrong",
           "#FFFFFF", "#FFFFFF", NOTIF, 60, 24, tint='\n    android:tint="#FFFFFF"'))
(out / "shep-mark.svg").write_text(svg(LAUNCHER, 108))
(out / "mono.svg").write_text(svg(LAUNCHER, 108, mono=True))

for name, g, vp in (("launcher", LAUNCHER, 108), ("notification", NOTIF, 60)):
    _, _, radius, s_w = g
    print(f"{name:13} viewport {vp:3}  corner radius {radius:5.2f}  "
          f"(circle mask {vp/3:.0f})  s width {s_w:.2f}")
